### ISSUE TITLE
All boxes are wrongly checked in Preferences

### ISSUE THREAD

**Issue by leowill01** [lusignan/RStudio-Material-Theme#1]
Hi, I've come across this in other themes as well, but evidently this theme also displays all checkboxes as checked in all panes in preferences even when they aren't:

<img width="815" alt="Screen Shot 2020-12-09 at 1 26 53 PM" src="https://user-images.githubusercontent.com/43548130/101683605-63a52b00-3a22-11eb-8b33-ed9fb459313d.png">

This goes for all checboxes on all other Preferences panes as well so it's impossible to really know which boxes I actually do have checked.

Can you provide a fix to accurately display which preferences boxes are checked?

**Comment by lusignan** [comment]
I'll try to get that fixed today

**Comment by lusignan** [comment]
@leowill01 I think I fixed it. Can you let me know if it's working for you?

**Comment by leowill01** [comment]
@lusignan Yes it is working! Thank you.
